-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 16:28:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema qlNganHang
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `qlNganHang` ;

-- -----------------------------------------------------
-- Schema qlNganHang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qlNganHang` DEFAULT CHARACTER SET utf8 ;
USE `qlNganHang` ;

-- -----------------------------------------------------
-- Table `qlNganHang`.`KhachHang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`KhachHang` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`KhachHang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hoTen` VARCHAR(50) NOT NULL,
  `email` VARCHAR(12) NOT NULL,
  `phone` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`TaiKhoanNganHang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`TaiKhoanNganHang` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`TaiKhoanNganHang` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tenDangKy` VARCHAR(45) NULL,
  `tenGoiNho` VARCHAR(45) NULL,
  `soDu` DOUBLE NULL,
  `soTK` DOUBLE NOT NULL COMMENT 'Số tài khoản',
  `idKhachHang` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `soTK_UNIQUE` (`soTK` ASC),
  INDEX `fk_TaiKhoanNganHang_KhachHang1_idx` (`idKhachHang` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_TaiKhoanNganHang_KhachHang1`
    FOREIGN KEY (`idKhachHang`)
    REFERENCES `qlNganHang`.`KhachHang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`NhacNo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`NhacNo` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`NhacNo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTaiKhoanNH` INT NOT NULL,
  `idTaiKhoanTao` INT NOT NULL,
  `tienNo` DOUBLE NOT NULL COMMENT 'Là số tiền',
  `noiDung` VARCHAR(100) NULL,
  `tinhTrang` VARCHAR(45) NULL,
  `ngayTao` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ThongBaoNhacNo_TaiKhoanNganHang1_idx` (`idTaiKhoanNH` ASC),
  INDEX `fk_NhacNo_TaiKhoanNganHang1_idx` (`idTaiKhoanTao` ASC),
  CONSTRAINT `fk_ThongBaoNhacNo_TaiKhoanNganHang1`
    FOREIGN KEY (`idTaiKhoanNH`)
    REFERENCES `qlNganHang`.`TaiKhoanNganHang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NhacNo_TaiKhoanNganHang1`
    FOREIGN KEY (`idTaiKhoanTao`)
    REFERENCES `qlNganHang`.`TaiKhoanNganHang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`LichSuChuyenKhoan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`LichSuChuyenKhoan` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`LichSuChuyenKhoan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ngay` DATETIME NOT NULL,
  `idTaiKhoanNHGui` INT NOT NULL,
  `soTaiKhoanNhan` VARCHAR(100) NOT NULL,
  `giaoDich` DOUBLE NOT NULL COMMENT 'Là số tiền',
  `noiDungChuyen` VARCHAR(100) NULL,
  `nganHangNhan` VARCHAR(45) NULL,
  `idNhacNo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LichSuChuyenKhoan_TaiKhoan1_idx` (`idTaiKhoanNHGui` ASC),
  INDEX `fk_LichSuChuyenKhoan_NhacNo1_idx` (`idNhacNo` ASC),
  CONSTRAINT `fk_LichSuChuyenKhoan_TaiKhoan1`
    FOREIGN KEY (`idTaiKhoanNHGui`)
    REFERENCES `qlNganHang`.`TaiKhoanNganHang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LichSuChuyenKhoan_NhacNo1`
    FOREIGN KEY (`idNhacNo`)
    REFERENCES `qlNganHang`.`NhacNo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`BangPhi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`BangPhi` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`BangPhi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Phi` DOUBLE NULL DEFAULT 0,
  `MoTa` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`ThietLapNguoiNhan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`ThietLapNguoiNhan` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`ThietLapNguoiNhan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idTaiKhoanNHGui` INT NOT NULL,
  `soTaiKhoanNhan` VARCHAR(45) NOT NULL,
  `nganHang` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DanhSachNguoiNhan_TaiKhoan1_idx` (`idTaiKhoanNHGui` ASC),
  CONSTRAINT `fk_DanhSachNguoiNhan_TaiKhoan1`
    FOREIGN KEY (`idTaiKhoanNHGui`)
    REFERENCES `qlNganHang`.`TaiKhoanNganHang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`LichSuNhanTien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`LichSuNhanTien` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`LichSuNhanTien` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ngay` DATETIME NOT NULL,
  `idTaiKhoanNHNhan` INT NOT NULL,
  `soTaiKhoanGui` VARCHAR(100) NULL,
  `giaoDich` VARCHAR(45) NULL COMMENT 'Là số tiền',
  `nganHangGui` VARCHAR(45) NULL,
  `noiDungNhan` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LichSuNhanTien_TaiKhoan1_idx` (`idTaiKhoanNHNhan` ASC),
  CONSTRAINT `fk_LichSuNhanTien_TaiKhoan1`
    FOREIGN KEY (`idTaiKhoanNHNhan`)
    REFERENCES `qlNganHang`.`TaiKhoanNganHang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`VaiTro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`VaiTro` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`VaiTro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `moTa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`NhanVien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`NhanVien` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`NhanVien` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `hoTen` VARCHAR(45) NULL,
  `diaChi` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `idVaiTro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_NhanVien_VaiTro1_idx` (`idVaiTro` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  CONSTRAINT `fk_NhanVien_VaiTro1`
    FOREIGN KEY (`idVaiTro`)
    REFERENCES `qlNganHang`.`VaiTro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qlNganHang`.`TaiKhoanTietKiem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qlNganHang`.`TaiKhoanTietKiem` ;

CREATE TABLE IF NOT EXISTS `qlNganHang`.`TaiKhoanTietKiem` (
  `id` INT NOT NULL,
  `idTaiKhoan` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TaiKhoanTietKiem_TaiKhoanNganHang1_idx` (`idTaiKhoan` ASC) ,
  CONSTRAINT `fk_TaiKhoanTietKiem_TaiKhoanNganHang1`
    FOREIGN KEY (`idTaiKhoan`)
    REFERENCES `qlNganHang`.`TaiKhoanNganHang` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
